# This file is a template, and might need editing before it works on your project.
image: debian:latest

before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python python3 tox
  - python -V                                   # Print out python version for debugging

test:
    stage: test
    script:
        tox
