# This file is a template, and might need editing before it works on your project.
image: python:latest

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

before_script:
  - python -V                                   # Print out python version for debugging
  - python setup.py build

test:
  script:
  - pip install tox
  - tox -e py36,flake8

pages:
  script:
  - pip install sphinx sphinx-rtd-theme
  - cd doc ; make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
