# This file is a template, and might need editing before it works on your project.
image: python:latest

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

before_script:
  - python -V                                   # Print out python version for debugging
  - pip install tox

test:
    script:
        tox -e py36,flake8
