variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

before_script:
  - python -V                                   # Print out python version for debugging
  - apt update && apt install -y python3-dev
  - python setup.py build

# GitLab CI doesn't support build matrices, yet:
#
# https://gitlab.com/gitlab-org/gitlab/issues/15356
#
# So we use a job template to avoid mindless repetition.  All of our
# jobs run 'tox', and we vary which tox environment they run or which
# Python version they use by overriding the 'TOXENV' environment
# variable or the 'image' job parameter.
#
# The name of the template starts with a dot to prevent GitLab from
# running it as an actual job.
.tox:
  image: python:latest
  before_script:
    - pip install tox
  script:
    - tox
  variables:
    TOXENV: py
    # The environment 'py' uses the version of Python used to invoke tox,
    # which allows us to test various Python versions by changing the
    # Docker image version in use.

# match this list of python versions with the classifiers variable in
# setup.py. see also the list in .gitlab-ci.yml, which is specific to
# the docker container running the tests
test-3.5:
  extends: .tox
  image: python:3.5

test-3.6:
  extends: .tox
  image: python:3.6

test-3.7:
  extends: .tox
  image: python:3.7

test-3.8:
  extends: .tox
  image: python:3.8

flake8:
  extends: .tox
  variables:
    TOXENV: flake8

black:
  extends: .tox
  variables:
    TOXENV: black
